<Project>

  <PropertyGroup>
    <TargetFramework Condition="'$(MSBuildProjectName)' != 'ZlibSharp'">net10.0</TargetFramework>
    <TargetFrameworks Condition="'$(MSBuildProjectName)' == 'ZlibSharp'">netstandard2.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>
    <SignAssembly>True</SignAssembly>
    <LangVersion>latest</LangVersion>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)Elskom.snk</AssemblyOriginatorKeyFile>
    <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts</PackageOutputPath>
    <!--
        The second and third entries here are the .NET 11 and the .NET 11 Transport Package sources.
    -->
    <RestoreAdditionalProjectSources>
        $(RestoreAdditionalProjectSources);
        https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet11/nuget/v3/index.json;
        https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet11-transport/nuget/v3/index.json;
        $(PackageOutputPath)
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

</Project>
