<Project>

  <Import Project="../../Directory.Build.props" />

  <PropertyGroup>
    <Version>1.0.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReleaseNotes>
      - Made an Adler32 hashing class that mirrors the entire API of the Crc32 class in the System.IO.Hashing nuget package.
    </PackageReleaseNotes>
    <Description>
      A high performance .NET hashing library that provides the ability to calculate an Adler32 hash.
    </Description>
    <IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">True</IsTrimmable>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">True</IsAotCompatible>
  </PropertyGroup>

</Project>
