<Project>

  <ItemGroup>
    <Using Include="System.Buffers" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="System.Reflection" />
    <Using Include="System.Runtime.CompilerServices" />
    <Using Include="System.Runtime.InteropServices" />
    <Using Include="System.Runtime.Loader" />
    <Using Include="System.Runtime.Serialization" />
    <Using Include="System.Runtime.Versioning" />
    <Using Include="System.Text" />
    <Using Include="ZlibSharp.Internal" />
  </ItemGroup>

</Project>
