<Project>

  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'netstandard2.0'" Include="System.Runtime.Loader" Version="*" />
    <PackageReference Condition="'$(TargetFramework)' == 'netstandard2.0'" Include="System.Memory" Version="*" />
    <!-- Need to reference the native library packages so users of ZlibSharp would automatically get them inside of their build output folders. -->
    <PackageReference Include="ZlibSharp.Native.win" Version="*" />
    <PackageReference Include="ZlibSharp.Native.linux" Version="*" />
    <PackageReference Include="ZlibSharp.Native.osx" Version="*" />
    <PackageReference Include="System.IO.Hashing" Version="*-*" />
  </ItemGroup>

</Project>
