<Project>

  <ItemGroup Condition="'$(MSBuildProjectExtension)' != '.csproj'">
    <ClInclude Include="main.hpp" />
    <ClInclude Include="chunk.hpp" />
    <ClInclude Include="zlib_utils.hpp" />
    <ClInclude Include=".\zlib\deflate.h" />
    <ClInclude Include=".\zlib\gzguts.h" />
    <ClInclude Include=".\zlib\inffast.h" />
    <ClInclude Include=".\zlib\inffixed.h" />
    <ClInclude Include=".\zlib\inflate.h" />
    <ClInclude Include=".\zlib\inftrees.h" />
    <ClInclude Include=".\zlib\trees.h" />
    <ClInclude Include=".\zlib\zconf.h" />
    <ClInclude Include=".\zlib\zlib.h" />
    <ClInclude Include=".\zlib\zutil.h" />
  </ItemGroup>

  <ItemGroup Condition="'$(MSBuildProjectExtension)' != '.csproj'">
    <ClCompile Include="main.cpp" />
    <ClCompile Include=".\zlib\adler32.c" />
    <ClCompile Include=".\zlib\compress.c" />
    <ClCompile Include=".\zlib\crc32.c" />
    <ClCompile Include=".\zlib\deflate.c" />
    <ClCompile Include=".\zlib\gzclose.c" />
    <ClCompile Include=".\zlib\gzlib.c" />
    <ClCompile Include=".\zlib\gzread.c" />
    <ClCompile Include=".\zlib\gzwrite.c" />
    <ClCompile Include=".\zlib\infback.c" />
    <ClCompile Include=".\zlib\inffast.c" />
    <ClCompile Include=".\zlib\inflate.c" />
    <ClCompile Include=".\zlib\inftrees.c" />
    <ClCompile Include=".\zlib\trees.c" />
    <ClCompile Include=".\zlib\uncompr.c" />
    <ClCompile Include=".\zlib\zutil.c" />
    <None Include="cpp.hint" />
  </ItemGroup>

</Project>
