# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@main
    - name: Install latest .NET SDK
      uses: Elskom/setup-latest-dotnet@main
      with:
        SDK_VERSION: '7.0.100-rc.2.22477.23'
        RUNTIME_VERSIONS: '6.0.x'

    - name: Install zlib from homebrew
      if: matrix.os == 'macos-latest'
      run: brew install zlib@1.2.11

    - name: Restore, Build, Test, and pack
      uses: Elskom/build-dotnet@main
      with:
        TEST: true
